# Generated by Django 4.0.4 on 2022-06-03 10:37

import analysis_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField(max_length=1000, verbose_name='Наименование организации-заказчика')),
                ('substation_name', models.TextField(max_length=1000, verbose_name='Наименование Подстанции')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='Диспетчерское наименование оборудования')),
                ('equipment_type_full', models.TextField(verbose_name='Наименование типа оборудования')),
                ('equipment_type', models.CharField(max_length=100, verbose_name='Тип оборудования')),
                ('testing_part', models.TextField(max_length=100, verbose_name='Место отбора')),
                ('equipment_serial_number', models.CharField(max_length=100, verbose_name='Заводской номер')),
            ],
            options={
                'verbose_name': 'Обследоваемое оборудование',
                'verbose_name_plural': 'Обследоваемое оборудование',
            },
        ),
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.TextField(max_length=100, verbose_name='Наименование оборудования')),
                ('device_type', models.CharField(max_length=100, verbose_name='Тип оборудования')),
                ('device_serial_number', models.IntegerField(default=None, verbose_name='Серийный номер хроматографа')),
                ('device_certification_number', models.CharField(max_length=100, verbose_name='Свидетельство о поверке')),
                ('next_device_certification_date', models.DateField(null=True, verbose_name='Дата следующей поверки')),
            ],
            options={
                'verbose_name': 'Диагностирующее оборудование',
                'verbose_name_plural': 'Диагностирующее оборудование',
            },
        ),
        migrations.CreateModel(
            name='analysis_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_name', models.CharField(max_length=100, verbose_name='Наименование протокола')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('protocol_status', models.CharField(max_length=100, verbose_name='Статус данного протокола')),
                ('fk_client_equipment_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.client_equipment', verbose_name='Идентификатор диагностируемого оборудования')),
                ('fk_devices_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.devices', verbose_name='Идентификатор диагностирующего хроматографа')),
            ],
            options={
                'verbose_name': 'Информация об анализах',
                'verbose_name_plural': 'Информация об анализах',
            },
        ),
    ]
