# Generated by Django 4.0.4 on 2022-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis_info',
            name='protocol_status',
            field=models.CharField(choices=[('generated', 'сгенерирован'), ('not generated', 'не сгенерирован')], max_length=100, verbose_name='Статус данного протокола'),
        ),
    ]
