# Generated by Django 4.0.4 on 2022-06-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0002_alter_analysis_info_protocol_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_equipment',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Наименование организации-заказчика'),
        ),
        migrations.AlterField(
            model_name='client_equipment',
            name='equipment_type_full',
            field=models.CharField(max_length=100, verbose_name='Наименование типа оборудования'),
        ),
        migrations.AlterField(
            model_name='client_equipment',
            name='substation_name',
            field=models.CharField(max_length=100, verbose_name='Наименование Подстанции'),
        ),
        migrations.AlterField(
            model_name='client_equipment',
            name='testing_part',
            field=models.CharField(max_length=100, verbose_name='Место отбора'),
        ),
    ]
