# Generated by Django 4.0.4 on 2022-09-02 10:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0009_alter_analysis_results_n2_o2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilBrandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_brand', models.CharField(max_length=100, verbose_name='Марка масла')),
            ],
            options={
                'verbose_name': 'Марка масла',
                'verbose_name_plural': 'Марки масел',
            },
        ),
        migrations.CreateModel(
            name='OilTestTypesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=20, verbose_name='Название испытания')),
                ('normative_doc', models.CharField(max_length=100, verbose_name='Нормативный документ')),
            ],
            options={
                'verbose_name': 'Информация о типах проводимых испытаний',
                'verbose_name_plural': 'Информация о типах проводимых испытаний',
            },
        ),
        migrations.CreateModel(
            name='ProbeDetailsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_date', models.DateField(default=django.utils.timezone.now)),
                ('bottle_num', models.CharField(max_length=20, verbose_name='Номер бутылки')),
                ('atm_temperature', models.CharField(max_length=20, verbose_name='Температура окружающей среды')),
                ('oil_temperature', models.CharField(max_length=20, verbose_name='Температура масла')),
                ('load_value', models.CharField(max_length=20, verbose_name='Нагрузка во время отбора')),
                ('def_type', models.CharField(max_length=100, verbose_name='Тип защиты')),
                ('oil_brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.oilbrandinfo', verbose_name='Марка масла')),
                ('probe_issue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.oiltesttypesinfo', verbose_name='Отбор для')),
            ],
            options={
                'verbose_name': 'Информация об отборе',
                'verbose_name_plural': 'Информация об отборе',
            },
        ),
    ]
