# Generated by Django 4.0.4 on 2022-09-02 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_app', '0010_oilbrandinfo_oiltesttypesinfo_probedetailsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilNormativeDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normative_doc', models.CharField(max_length=100, verbose_name='Нормативный документ')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
            },
        ),
        migrations.AddField(
            model_name='probedetailsinfo',
            name='tested_client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.client_equipment', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='probedetailsinfo',
            name='tester_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Прозводивший отбор'),
        ),
        migrations.AlterField(
            model_name='oiltesttypesinfo',
            name='normative_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.oilnormativedocs', verbose_name='Нормативные документ'),
        ),
    ]
