# Generated by Django 4.0.4 on 2022-09-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0011_oilnormativedocs_probedetailsinfo_tested_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probedetailsinfo',
            name='syringe_num',
            field=models.CharField(default=None, max_length=20, verbose_name='Номер шприца'),
        ),
    ]
