# Generated by Django 4.0.4 on 2022-10-06 16:12

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_app', '0012_probedetailsinfo_syringe_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformersLimitValues_35_220_STO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_class', models.IntegerField(verbose_name='Название вида оборудования')),
                ('def_type', models.CharField(max_length=100, verbose_name='Наименование протокола')),
                ('years_periods_include', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('srg_limit_value', models.FloatField()),
                ('h2_limit_value', models.FloatField()),
                ('ch4_limit_value', models.FloatField()),
                ('c2h6_limit_value', models.FloatField()),
                ('c2h4_limit_value', models.FloatField()),
                ('c2h2_limit_value', models.FloatField()),
                ('co_limit_value', models.FloatField()),
                ('co2_limit_value', models.FloatField()),
                ('oil_brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('rpn_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('load', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
            options={
                'verbose_name': 'Предельные концентрации газов',
                'verbose_name_plural': 'Предельная концентрация газов',
            },
        ),
        migrations.AlterField(
            model_name='client_equipment',
            name='equipment_type_full',
            field=models.CharField(max_length=100, verbose_name='Название вида оборудования'),
        ),
        migrations.AlterField(
            model_name='probedetailsinfo',
            name='probe_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата отбора'),
        ),
        migrations.AlterField(
            model_name='probedetailsinfo',
            name='tester_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Производивший отбор'),
        ),
    ]
