# Generated by Django 4.0.4 on 2022-10-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0013_transformerslimitvalues_35_220_sto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='load',
            new_name='equipment_power',
        ),
    ]
