# Generated by Django 4.0.4 on 2022-10-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0014_rename_load_transformerslimitvalues_35_220_sto_equipment_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefTypeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_type', models.CharField(max_length=100, verbose_name='Тип защиты')),
            ],
            options={
                'verbose_name': 'тип защиты',
                'verbose_name_plural': 'типы защиты',
            },
        ),
        migrations.CreateModel(
            name='EquipmentVoltageClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_class', models.IntegerField(default=0, verbose_name='Класс напряжения, кВ')),
            ],
            options={
                'verbose_name': 'класс напряжения',
                'verbose_name_plural': 'классы напряжения',
            },
        ),
        migrations.CreateModel(
            name='RpnTypeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpn_type', models.CharField(max_length=100, verbose_name='Тип РПН')),
            ],
            options={
                'verbose_name': 'тип РПН',
                'verbose_name_plural': 'типы РПН',
            },
        ),
        migrations.AlterModelOptions(
            name='oilbrandinfo',
            options={'verbose_name': 'марку масла', 'verbose_name_plural': 'марки масел'},
        ),
        migrations.AlterModelOptions(
            name='transformerslimitvalues_35_220_sto',
            options={'verbose_name': 'Предельные концентрации газов СТО 34.01-23-003-2019', 'verbose_name_plural': 'Предельная концентрация газов СТО 34.01-23-003-2019'},
        ),
        migrations.AddField(
            model_name='client_equipment',
            name='equipment_power',
            field=models.IntegerField(default=0, verbose_name='Мощность трансформатора, МВт'),
        ),
        migrations.AddField(
            model_name='client_equipment',
            name='oil_brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.oilbrandinfo', verbose_name='Марка масла'),
        ),
        migrations.AddField(
            model_name='client_equipment',
            name='usage_years',
            field=models.IntegerField(default=0, verbose_name='Число лет использования'),
        ),
        migrations.AddField(
            model_name='client_equipment',
            name='def_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.deftypeinfo', verbose_name='Тип защиты'),
        ),
        migrations.AddField(
            model_name='client_equipment',
            name='rpn_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.rpntypeinfo', verbose_name='Тип РПН'),
        ),
        migrations.AddField(
            model_name='client_equipment',
            name='voltage_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.equipmentvoltageclasses', verbose_name='Класс напряжения'),
        ),
    ]
