# Generated by Django 4.0.4 on 2022-10-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0015_deftypeinfo_equipmentvoltageclasses_rpntypeinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='c2h2_limit_value',
            new_name='c2h2_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='c2h4_limit_value',
            new_name='c2h4_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='c2h6_limit_value',
            new_name='c2h6_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='ch4_limit_value',
            new_name='ch4_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='co2_limit_value',
            new_name='co2_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='co_limit_value',
            new_name='co_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='h2_limit_value',
            new_name='h2_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='srg_limit_value',
            new_name='srg_limit_value_dz',
        ),
    ]
