# Generated by Django 4.0.4 on 2022-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0016_rename_c2h2_limit_value_transformerslimitvalues_35_220_sto_c2h2_limit_value_dz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformerDefTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('def_type', models.CharField(max_length=100, verbose_name='Тип защиты')),
            ],
            options={
                'verbose_name': 'тип защиты',
                'verbose_name_plural': 'типы защит',
            },
        ),
    ]
