# Generated by Django 4.0.4 on 2022-10-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0017_transformerdeftypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransformerDefTypes',
        ),
    ]
