# Generated by Django 4.0.4 on 2022-10-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0019_rename_deftypeinfo_transformerdeftypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentAndTestingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type_full', models.CharField(max_length=100, verbose_name='Вид оборудования')),
                ('testing_part', models.CharField(max_length=100, verbose_name='Место отбора')),
            ],
            options={
                'verbose_name': 'оборудование и место отбора',
                'verbose_name_plural': 'оборудования и места отбора',
            },
        ),
        migrations.AlterModelOptions(
            name='client_equipment',
            options={'verbose_name': 'заказчик и его оборудование', 'verbose_name_plural': 'заказчики и их оборудование'},
        ),
        migrations.RemoveField(
            model_name='client_equipment',
            name='oil_brand',
        ),
        migrations.RemoveField(
            model_name='client_equipment',
            name='testing_part',
        ),
        migrations.RemoveField(
            model_name='probedetailsinfo',
            name='def_type',
        ),
        migrations.AddField(
            model_name='probedetailsinfo',
            name='testing_part',
            field=models.CharField(default=None, max_length=100, verbose_name='Место отбора'),
        ),
        migrations.AlterField(
            model_name='client_equipment',
            name='equipment_type_full',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.equipmentandtestingpart', verbose_name='Вид оборудования'),
        ),
    ]
