# Generated by Django 4.0.4 on 2022-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0020_equipmentandtestingpart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_equipment',
            name='equipment_type_full',
            field=models.CharField(max_length=100, verbose_name='Вид оборудования'),
        ),
        migrations.AlterField(
            model_name='client_equipment',
            name='substation_name',
            field=models.CharField(max_length=100, verbose_name='Наименование подстанции'),
        ),
    ]
