# Generated by Django 4.0.4 on 2022-10-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0024_analysis_results_probe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probedetailsinfo',
            name='probe_issue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.oilprobesissues', verbose_name='Причина отбора'),
        ),
    ]
