# Generated by Django 4.0.4 on 2022-10-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0026_rename_c2h2_analysis_results_c2h2_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='c2h2_limit_value_dz',
            new_name='C2H2_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='c2h4_limit_value_dz',
            new_name='C2H4_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='c2h6_limit_value_dz',
            new_name='C2H6_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='ch4_limit_value_dz',
            new_name='CH4_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='co2_limit_value_dz',
            new_name='CO2_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='co_limit_value_dz',
            new_name='CO_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='h2_limit_value_dz',
            new_name='H2_limit_value_dz',
        ),
        migrations.RenameField(
            model_name='transformerslimitvalues_35_220_sto',
            old_name='srg_limit_value_dz',
            new_name='SRG_limit_value_dz',
        ),
    ]
