# Generated by Django 4.0.4 on 2022-10-14 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0028_analysis_results_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_equipment',
            name='production_year',
            field=models.PositiveIntegerField(default=None, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='Год изготовления'),
        ),
        migrations.AddField(
            model_name='client_equipment',
            name='setting_year',
            field=models.PositiveIntegerField(default=None, help_text='Use the following format: <YYYY>', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2022)], verbose_name='Год установки'),
        ),
    ]
