# Generated by Django 4.0.4 on 2022-10-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('analysis_app', '0031_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='contenttypes.contenttype'),
        ),
    ]
