# Generated by Django 4.0.4 on 2022-10-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0032_alter_status_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='request_type',
        ),
        migrations.AddField(
            model_name='status',
            name='equipment_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analysis_app.equipmentandtestingpart'),
        ),
        migrations.AddField(
            model_name='status',
            name='limit_values',
            field=models.ManyToManyField(to='analysis_app.transformerslimitvalues_35_220_sto'),
        ),
        migrations.AddField(
            model_name='status',
            name='test_type_and_doc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analysis_app.oiltesttypesinfo'),
        ),
    ]
