# Generated by Django 4.0.4 on 2022-10-18 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0033_remove_status_request_id_remove_status_request_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='equipment_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_app.equipmentandtestingpart'),
        ),
        migrations.AlterField(
            model_name='status',
            name='test_type_and_doc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis_app.oiltesttypesinfo'),
        ),
    ]
