# Generated by Django 4.0.4 on 2022-10-18 14:52

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0040_chargtransformerslimitvalues_35_220_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargTransformersLimitValues_35_500',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normative_doc', models.CharField(max_length=100, verbose_name='Наименование НТД')),
                ('voltage_class', models.IntegerField(verbose_name='Название вида оборудования')),
                ('def_type', models.CharField(max_length=100, verbose_name='Наименование протокола')),
                ('years_periods_include', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('SRG_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('H2_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('CH4_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('C2H6_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('C2H4_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('C2H2_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('CO_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('CO2_limit_value_pdz', models.FloatField(blank=True, null=True)),
                ('SRG_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('H2_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('CH4_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('C2H6_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('C2H4_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('C2H2_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('CO_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('CO2_limit_value_dz', models.FloatField(blank=True, null=True)),
                ('oil_brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('rpn_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('equipment_power', django.contrib.postgres.fields.ranges.IntegerRangeField()),
            ],
            options={
                'verbose_name': 'Предельные концентрации газов трансформаторов 35-500 кВ',
                'verbose_name_plural': 'Предельная концентрация газов трансформаторов 35-500 кВ',
            },
        ),
        migrations.DeleteModel(
            name='ChargTransformersLimitValues_35_220',
        ),
        migrations.AlterField(
            model_name='status',
            name='limit_values',
            field=models.ManyToManyField(to='analysis_app.chargtransformerslimitvalues_35_500'),
        ),
    ]
