# Generated by Django 4.0.4 on 2023-03-30 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis_app', '0042_companydetails_analysis_results_protocol_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='oil_PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата проведения анализа')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки пробы в лабораторию')),
                ('probe_code', models.CharField(default=None, max_length=30, verbose_name='Шифр пробы')),
                ('description', models.TextField(blank=True, max_length=266, null=True, verbose_name='Заметки')),
                ('color_value', models.TextField(max_length=12, verbose_name='Цвет')),
                ('transparency_value', models.TextField(max_length=12, verbose_name='Прозрачность')),
                ('BV_CV_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='Пробивное напряжение/коэффициент')),
                ('moisture_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='Влажность')),
                ('flash_rate_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='Темп вспышки')),
                ('acid_number_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='Кислотное число')),
                ('KPC_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='КПЧ')),
                ('ph_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='кисл и щелч')),
                ('ionol_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='ионол')),
                ('furan_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='фуран')),
                ('tan_d_value', models.TextField(blank=True, max_length=12, null=True, verbose_name='тангенс d')),
                ('protocol_code', models.CharField(default=0, max_length=50, verbose_name='Шифр протокола')),
                ('test_condition_temp', models.TextField(default=None, max_length=4, verbose_name='Температура помещения, °C')),
                ('test_condition_humidity', models.TextField(default=None, max_length=4, verbose_name='Влажность, %')),
                ('test_condition_pressure', models.TextField(default=None, max_length=4, verbose_name='Давление, мм.рт.ст.')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.client_equipment', verbose_name='Заказчик - оборудование')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
                ('probe_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.probedetailsinfo', verbose_name='Проба из отбора')),
            ],
            options={
                'verbose_name': 'Проведенные анализы',
                'verbose_name_plural': 'Проведенные анализы',
            },
        ),
    ]
