# Generated by Django 4.0.4 on 2023-04-04 05:27

import django.contrib.postgres.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0043_oil_pc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oil_pc',
            options={'verbose_name': 'Проведенные анализы ФХ', 'verbose_name_plural': 'Проведенные анализы ФХ'},
        ),
        migrations.CreateModel(
            name='PC_LimitValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normative_doc', models.CharField(max_length=100, verbose_name='Наименование НТД')),
                ('voltage_class', models.IntegerField(verbose_name='Класс напряжения')),
                ('def_type', models.CharField(max_length=100, verbose_name='Тип защиты')),
                ('color_limit_value_ons', models.TextField(blank=True, null=True)),
                ('transparency_limit_value_ons', models.TextField(blank=True, null=True)),
                ('BV_CV_limit_value_ons', models.TextField(blank=True, null=True)),
                ('moisture_limit_value_ons', models.TextField(blank=True, null=True)),
                ('flash_rate_limit_value_ons', models.TextField(blank=True, null=True)),
                ('acid_number_limit_value_ons', models.TextField(blank=True, null=True)),
                ('KPC_limit_value_ons', models.TextField(blank=True, null=True)),
                ('ph_limit_value_ons', models.TextField(blank=True, null=True)),
                ('ionol_limit_value_ons', models.TextField(blank=True, null=True)),
                ('furan_limit_value_ons', models.TextField(blank=True, null=True)),
                ('tan_d_limit_value_ons', models.TextField(blank=True, null=True)),
                ('color_limit_value_pd', models.TextField(blank=True, null=True)),
                ('transparency_limit_value_pd', models.TextField(blank=True, null=True)),
                ('BV_CV_limit_value_pd', models.TextField(blank=True, null=True)),
                ('moisture_limit_value_pd', models.TextField(blank=True, null=True)),
                ('flash_rate_limit_value_pd', models.TextField(blank=True, null=True)),
                ('acid_number_limit_value_pd', models.TextField(blank=True, null=True)),
                ('KPC_limit_value_pd', models.TextField(blank=True, null=True)),
                ('ph_limit_value_pd', models.TextField(blank=True, null=True)),
                ('ionol_limit_value_pd', models.TextField(blank=True, null=True)),
                ('furan_limit_value_pd', models.TextField(blank=True, null=True)),
                ('tan_d_limit_value_pd', models.TextField(blank=True, null=True)),
                ('oil_brand', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('rpn_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('equipment_power', django.contrib.postgres.fields.ranges.IntegerRangeField()),
                ('probe_issue', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='analysis_app.oilprobesissues', verbose_name='Причина отбора')),
            ],
            options={
                'verbose_name': 'Предельные значения ФХ анализа',
                'verbose_name_plural': 'Предельные значения ФХ анализа',
            },
        ),
    ]
