# Generated by Django 4.0.4 on 2023-04-04 05:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0044_alter_oil_pc_options_pc_limitvalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc_limitvalues',
            name='color_limit_value_ons',
        ),
        migrations.RemoveField(
            model_name='pc_limitvalues',
            name='color_limit_value_pd',
        ),
        migrations.RemoveField(
            model_name='pc_limitvalues',
            name='equipment_power',
        ),
        migrations.RemoveField(
            model_name='pc_limitvalues',
            name='rpn_type',
        ),
        migrations.RemoveField(
            model_name='pc_limitvalues',
            name='transparency_limit_value_ons',
        ),
        migrations.RemoveField(
            model_name='pc_limitvalues',
            name='transparency_limit_value_pd',
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='KPC_value',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='КПЧ'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='acid_number_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='Кислотное число'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='color_value',
            field=models.TextField(max_length=25, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='furan_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='фуран'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='ionol_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='ионол'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='moisture_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='ph_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='кисл и щелч'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='tan_d_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='тангенс d'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='transparency_value',
            field=models.TextField(max_length=25, verbose_name='Прозрачность'),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='BV_CV_limit_value_ons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='BV_CV_limit_value_pd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='KPC_limit_value_ons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='KPC_limit_value_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='acid_number_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='acid_number_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='flash_rate_limit_value_ons',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='flash_rate_limit_value_pd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='furan_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='furan_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='ionol_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='ionol_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='moisture_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='moisture_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='oil_brand',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None, verbose_name='Марка масла'),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='ph_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='ph_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='tan_d_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pc_limitvalues',
            name='tan_d_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
