# Generated by Django 4.0.4 on 2023-04-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0045_remove_pc_limitvalues_color_limit_value_ons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil_pc',
            name='gas_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='газосодержание'),
        ),
        migrations.AddField(
            model_name='oil_pc',
            name='sludge_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='общее содержание шлама'),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='gas_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='gas_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='sludge_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='sludge_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='KPC_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='КПЧ'),
        ),
        migrations.AlterField(
            model_name='oil_pc',
            name='moisture_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='Влагосодержание'),
        ),
    ]
