# Generated by Django 4.0.4 on 2023-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0046_oil_pc_gas_value_oil_pc_sludge_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_limitvalues',
            name='color_value_pd',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='transparency_value_pd',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Прозрачность'),
        ),
    ]
