# Generated by Django 4.0.4 on 2023-04-08 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0047_pc_limitvalues_color_value_pd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc_limitvalues',
            old_name='color_value_pd',
            new_name='color_limit_value_pd',
        ),
        migrations.RenameField(
            model_name='pc_limitvalues',
            old_name='transparency_value_pd',
            new_name='transparency_limit_value_pd',
        ),
    ]
