# Generated by Django 4.0.4 on 2023-04-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0048_rename_color_value_pd_pc_limitvalues_color_limit_value_pd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil_pc',
            name='corrosive_sulfur',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='содержание коррозийной серы'),
        ),
        migrations.AddField(
            model_name='oil_pc',
            name='oxidation_stability_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='стабильность против окисления'),
        ),
        migrations.AddField(
            model_name='oil_pc',
            name='solidification_value',
            field=models.IntegerField(blank=True, max_length=12, null=True, verbose_name='Температура застывания'),
        ),
        migrations.AddField(
            model_name='oil_pc',
            name='sulfur_value',
            field=models.FloatField(blank=True, max_length=12, null=True, verbose_name='содержание серы'),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='corrosive_sulfur_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='corrosive_sulfur_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='oxidation_stability_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='oxidation_stability_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='solidification_limit_value_ons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='solidification_limit_value_pd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='sulfur_limit_value_ons',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='sulfur_limit_value_pd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
