# Generated by Django 4.0.4 on 2023-04-10 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0050_alter_oil_pc_solidification_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oil_pc',
            old_name='corrosive_sulfur',
            new_name='corrosive_sulfur_value',
        ),
        migrations.RenameField(
            model_name='pc_limitvalues',
            old_name='corrosive_sulfur_ons',
            new_name='corrosive_sulfur_limit_value_ons',
        ),
        migrations.RenameField(
            model_name='pc_limitvalues',
            old_name='corrosive_sulfur_pd',
            new_name='corrosive_sulfur_limit_value_pd',
        ),
    ]
