# Generated by Django 4.0.4 on 2023-04-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0051_rename_corrosive_sulfur_oil_pc_corrosive_sulfur_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc_limitvalues',
            name='color_limit_value_ons',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='pc_limitvalues',
            name='transparency_limit_value_ons',
            field=models.TextField(blank=True, max_length=25, null=True, verbose_name='Прозрачность'),
        ),
    ]
